name: Build-Golang-Project
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/Build-Golang-Project.yml'
  schedule:
        - cron: 0 12 * * *

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  Gogs:
    name: Build Gogs
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15.2
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Clone Gogs From Github and Build
      if: success()
      run: |
        git clone https://github.com/gogs/gogs.git
        sudo apt update -qq
        sudo apt install -qq upx libpam0g-dev
        cd gogs
        node -v
        go version
        go build -tags "sqlite pam cert" -o gogs
        
    - name: UPX Binary Files to Reduce Size.
      if: success()
      run: |
        cd gogs
        upx -9 gogs -q
        
    - name: Upload Flies to Github Actions
      uses: actions/upload-artifact@master
      if: success()
      with:
       name: Gogs
       path: gogs/gogs 

  Gitea:
    name: Build Gitea
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15.2
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.2
  
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - name: Clone Gitea From Github and Build
      run: |
        git clone https://github.com/go-gitea/gitea.git
        cd gitea
        node -v
        go version
        TAGS="bindata sqlite sqlite_unlock_notify" make build
        
    - name: UPX Binary Files to Reduce Size.
      if: success()
      run: |
        cd gitea
        upx -9 gitea -q
        
    - name: Upload Flies to Github Actions
      uses: actions/upload-artifact@master
      if: success()
      with:
       name: Gitea
       path: gitea/gitea

  Nps:
    name: Build Nps
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15.2
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.2
  
    - name: Clone Nps From Github and Build
      run: |
        git clone https://github.com/ehang-io/nps.git
        cd nps
        go version
        bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/Golang-Project/Nps/build.sh) 
        
    - name: Upload Flies to Github Actions
      uses: actions/upload-artifact@master
      if: success()
      with:
       name: Nps
       path: nps/*.tar.gz


  Frp:
    name: Build Frp
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15.2
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.2

    - name: Clone Frp From Github and Build
      run: |
        git clone https://github.com/fatedier/frp.git
        cd frp
        go version
        bash package.sh
        
    - name: Upload Flies to Github Actions
      uses: actions/upload-artifact@master
      if: success()	
      with:	
       name: Frp	
       path: frp/release/packages/	


#  V2Ray:
#    name: Build V2Ray
#    runs-on: ubuntu-latest
#    steps:
#    - name: Set up Go 1.15.2
#      uses: actions/setup-go@v2
#      with:
#        go-version: 1.15.2
#    - name: Clone V2Ray From Github and Build
#      run: |
#        sudo apt update -qq
#        sudo apt install -qq upx jq git file pkg-config zip g++ zlib1g-dev unzip python openssl tree
#        mkdir go
#        export GOPATH=$PWD/go
#        go get -insecure -u v2ray.com/core/...
#        cd $GOPATH/src/v2ray.com/core
#        go version
#        sudo bazel build --sandbox_debug --action_env=GOPATH=$GOPATH --action_env=PATH=$PATH //release:all
#        cd bazel-bin/release
#        echo "::set-env name=V2BIN::$(pwd)"
#    - name: Upload Flies to Github Actions
#      uses: actions/upload-artifact@master
#      if: success()	
#      with:	
#       name: V2Ray
#       path: ${{ env.V2BIN }}/*.zip
#    - name: Upload V2Ray's Binary Files to Main Download Station.
#      if: success()	
#      run: |	
#        cd ${{ env.V2BIN }}
#        zip -r -o V2Ray.zip . -i *.zip
#        curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Software/ALL/V2Ray" -F "file=@V2Ray.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
#        curl --socks5 ${{ secrets.PROXY_ADDR }} -U ${{ secrets.PROXY_USER }} -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Software/ALL/V2Ray" -F "file=@V2Ray.zip" ${{ secrets.CN_STATION_PROCESSOR }}

